<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-J2EHUA6C" failures="1" tests="6" name="Test" time="35.235" errors="0" timestamp="2023-12-23T15:19:16 EST">
  <testcase classname="com.qa.tutorialsninja.TestCases.HomePageTest" name="verifyHomePage" time="0.505"/>
  <testcase classname="com.qa.tutorialsninja.TestCases.LoginTest" name="verifyLoginWithValidCredentials" time="1.093"/>
  <testcase classname="com.qa.tutorialsninja.TestCases.RegisterTest" name="verifyRegisterWithValidCredentials" time="1.619"/>
  <testcase classname="com.qa.tutorialsninja.TestCases.SearchProductTest" name="verifySearchWithValidProductsAndVerifyProductDetails" time="1.489"/>
  <testcase classname="com.qa.tutorialsninja.TestCases.ShoppingCartTest" name="verifyShoppingCart" time="0.602"/>
  <testcase classname="com.qa.tutorialsninja.TestCases.CheckOutTest" name="verifyCheckout" time="4.19">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.qa.tutorialsninja.TestCases.CheckOutTest.verifyCheckout(CheckOutTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyCheckout -->
</testsuite> <!-- Test -->
